---
pagetitle: "Schools in Trafford"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(crosstalk) ; library(tidyverse) ; library(sf) ; library(leaflet) ; library(leaflet.extras) ; library(reactable) ; library(shiny) ; library(htmlwidgets) ; library(htmltools)

# local authority boundary
sf <- st_read("data/local_authority.geojson", quiet = TRUE)

# schools
df <- read_csv("data/schools.csv") %>% 
  mutate(phase = fct_relevel(as_factor(phase),
                             level = c("Primary", "Secondary", "Further Education", "Continuous")),
         ofsted_rating = fct_relevel(as_factor(ofsted_rating),
                              level = c("Outstanding", "Good", "Requires improvement", "Serious Weaknesses")),
         website = ifelse(is.na(website), "", str_c("<a href='", website, "'target='_blank'>", str_remove(website, "http://www.|https://www.|www.|http://|https://"), "</a>")),
         popup = ifelse(is.na(ofsted_rating), str_c("<strong>", name, "</strong><br/><a href='", compare_performance, "'target='_blank'>Compare performance with other schools</a>") %>% map(HTML), str_c("<strong>", name, "</strong><br/><a href='", ofsted_report, "'target='_blank'>Latest Ofsted report</a><br/><a href='", compare_performance, "'target='_blank'>Compare performance with other schools</a>") %>% map(HTML)))  %>% 
  arrange(name)

# shared dataframe
sd <- SharedData$new(df, group = "name")
# subset of shared dataframe
sd_table <- select(df, name, headteacher, website, nursery_provision, sixth_form) %>%
  SharedData$new(group = "name")
```

```{r, map}
map <- leaflet(sd, width = "100%", height = 350) %>%
  addTiles(urlTemplate = "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a> | <a href="https://www.ons.gov.uk/methodology/geography/licences">Contains OS data © Crown copyright and database right (2020)</a> | Data: <a href="https://get-information-schools.service.gov.uk" target="_blank">DfE</a>', options = tileOptions(minZoom = 11, maxZoom = 18)) %>%
  addPolygons(data = sf, fillColor = "#CCCCCC", weight = 0.8, opacity = 1, color = "#212121") %>%  
  addAwesomeMarkers(popup = df$popup, icon = ~makeAwesomeIcon(icon = "fas fa-school", library = "fa", iconColor = "#FFFFFF", markerColor = "purple")) %>%
  addEasyButton(
    easyButton(
      position = "topleft",
      icon = "fa-crosshairs",
      title = "Locate me",
      onClick = JS(c("function(btn,  map){map.locate({setView:true,enableHighAccuracy: true })}")))) %>% 
  onRender(paste0("function(el, x) {$('head').append(","\'<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\'",");}"))
```

```{r, table}
# improve accessibility
options(reactable.language = reactableLang(
  noData = "No schools found",
  pagePreviousLabel = "Previous page",
  pageNextLabel = "Next page"))

table <- reactable(
  sd_table,
  resizable = TRUE,
  borderless = TRUE,
  wrap = FALSE,
  searchable = TRUE,
  highlight = TRUE,
  selection = "multiple",
  onClick = "select",
  rowStyle = list(cursor = "pointer"),
  columns = list(
    name = colDef(name = "School",
                  minWidth = 190,
                  style = list(position = "sticky", left = 0, background = "#fff", zIndex = 1),
                  headerStyle = list(position = "sticky", left = 0, background = "#fff", zIndex = 1)),
    headteacher = colDef(name = "Headteacher",
                         minWidth = 150),
    website = colDef(name = "Website", 
                     minWidth = 170,
                     html = TRUE),
    nursery_provision = colDef(name = "Nursery", 
                               cell = JS("function(cellInfo) {return cellInfo.value === 'No' ? '\u2718' : '\u2713'}")),
    sixth_form = colDef(name = "Sixth form",
                        cell = JS("function(cellInfo) {return cellInfo.value === 'No' ? '\u2718' : '\u2713'}")))
)
```

```{css}
@import url('https://use.fontawesome.com/releases/v5.10.1/css/all.css');

@import url('https://fonts.googleapis.com/css?family=Open+Sans%7CRoboto');

html, body {
  font-family: 'Open Sans', sans-serif;
}
        
h1, h2, h3, h4 {
  font-family: 'Roboto', sans-serif;
  color: #707070;
}

h2 {
  font-size: 1.6em;
}

.form-group {
  margin-bottom: 0px;
}
```

```{r, logo}
a(
  href = "https://www.trafforddatalab.io", 
  img(src = "https://www.trafforddatalab.io/assets/logo/trafforddatalab_logo.svg", 
      alt = "Trafford Data Lab", 
      width = "100",
      style = "position:absolute; top:0; right:0; padding: 10px;")
  )
```

```{r, ui}
div(class = "container-fluid",
    h1("Schools in Trafford", style = "padding-top: 25px; margin-bottom: 20px;"),
    div(class = "row",
        div(class = "col-xs-12 col-sm-6 col-md-6 col-lg-6", map),
        div(class = "col-xs-6 col-sm-3 col-md-3 col-lg-3", 
            list(
              # Phase
              filter_checkbox(id = "phase", label = "Phase", sharedData = sd, group = ~phase),
              # Type
              filter_checkbox(id = "type", label = "Type", sharedData = sd, group = ~type))),
        div(class = "col-xs-6 col-sm-3 col-md-3 col-lg-3", 
            list(
              # Gender
              filter_checkbox(id = "gender", label = "Gender", sharedData = sd, group = ~gender, inline = TRUE),
              br(),
              # Pupil count
              filter_slider(id = "number_of_pupils", label = "Number of pupils", sharedData = sd, column = ~number_of_pupils, step = 10, ticks = FALSE),
              br(),
              # FSM
              filter_slider(id = "percent_fsm", label = "Free School Meals", sharedData = sd, column = ~percent_fsm, step = 1, round = TRUE, sep = "", ticks = FALSE, post = "%"),
              br(),
              # Ofsted rating
              filter_checkbox(id = "ofsted_rating", label = "Ofsted rating", sharedData = sd, group = ~ofsted_rating)
              ))),
    br(),
    h2("School information", style = "margin-bottom: 15px;"),
    div(class = "row",
        div(class = "col-sm-12", table)),
    div(class = "row",
        div(class = "col-sm-12", 
            p("The data shown here was retrived on 11 June 2020 from the ", a("Department for Education's register of schools and colleges.", href = 'https://get-information-schools.service.gov.uk'), "The pupil count and the percentage of pupils on free school meals are drawn from a school audit conducted in January 2019."), 
            p("For more information about schools in Trafford, please visit ", a("Trafford Council's school pages", href = 'https://www.trafford.gov.uk/residents/schools/schools-in-trafford/schools-in-trafford.aspx', target = "_blank"))),
        br()
        )
    )
```